apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ManojAndroid/Social-Service.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
