apiVersion: v1
kind: Service
metadata:
  name: sso-service
spec:
  selector:
    app: sso-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: admin
      port: 9090
      targetPort: 9090
