apiVersion: v1
kind: Service
metadata:
  name: sso-service
  labels:
    app: sso-service
spec:
  selector:
    app: sso-service
  ports:
    - name: http-main
      port: 9090
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
    - name: admin
      port: 8082
      targetPort: 8082
